
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"

ignored = ["k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1"]

[[constraint]]
  name = "github.com/Sirupsen/logrus"
  version = "1.0.3"

[[constraint]]
  name = "github.com/blang/semver"
  version = "3.5.1"

[[constraint]]
  name = "github.com/docker/docker"
  version = "1.13.1"

[[constraint]]
  name = "github.com/docker/engine-api"
  version = "0.4.0"

[[constraint]]
  name = "github.com/docker/go-connections"
  version = "0.3.0"

[[constraint]]
  name = "github.com/docker/go-units"
  version = "0.3.2"

[[constraint]]
  name = "github.com/docker/machine"
  version = "0.13.0"

[[constraint]]
  branch = "master"
  name = "github.com/golang/glog"

[[constraint]]
  branch = "master"
  name = "github.com/jimmidyson/go-download"

[[constraint]]
  name = "github.com/magiconair/properties"
  version = "1.7.3"

[[constraint]]
  name = "github.com/opencontainers/runc"
  version = "0.1.1"

[[constraint]]
  name = "github.com/pborman/uuid"
  version = "1.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/pkg/browser"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.1"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/xeipuuv/gojsonschema"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  branch = "master"
  name = "golang.org/x/sys"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/yaml.v2"

[[constraint]]
  name = "github.com/ghodss/yaml"
  version = "1.0.0"
 
[[override]]
  name = "k8s.io/api"
  revision = "4b8fc5be9b77d91bbb6525d18591c43699a2b4e5"
 
[[override]]
  name = "k8s.io/client-go"
  version = "4.0.0"
  
[[override]]
  name = "k8s.io/apimachinery"
  revision = "1fd2e63a9a370677308a42f24fd40c86438afddf"
  
[[override]]
  name = "k8s.io/apiextensions-apiserver"
  branch = "release-1.7"
  
[[override]]
  name = "github.com/ugorji/go"
  revision = "ded73eae5db7e7a0ef6f55aace87a2873c5d2b74"  
  
[[override]]
  name = "k8s.io/kubernetes"
  revision = "d3ada0119e776222f11ec7945e6d860061339aad"
  
[[constraint]]
  name = "k8s.io/minikube"
  revision = "2deea5f75745698fd04f81da724716"
